### ISSUE TITLE
Enable Docker SSH to use multiple worker containers

### ISSUE THREAD

**Issue by pmcharrison** [Dallinger/Dallinger#6048]
Currently the Docker SSH launch route only launches one worker container. See `docker-compose-experiment.yml.j2`:

```
  worker:
    image: {{ experiment_image }}
    command: dallinger_heroku_worker
    depends_on: &commondepends
      redis_{{ experiment_id }}:
        condition: service_healthy
      pgbouncer:
        condition: service_started
    user: "${UID}:${GID}"
    environment: &commonenv
      REDIS_URL: redis://redis_{{ experiment_id }}:6379
      DATABASE_URL: postgresql://{{ experiment_id }}:{{ postgresql_password }}@{{ experiment_id }}_pgbouncer/{{ experiment_id }}
      HOME: /tmp
      HOST: 0.0.0.0
    {%- for key, value in config.items() %}
      {{ key }}: {{ value | string() | tojson }}
    {%- endfor %}
```

There is similar code in `docker-compose.yml.j2`.

We want to make the number of workers configurable via a config parameter, that defaults to 1. Something like `docker_n_workers`. Or maybe actually it's better to use the pre-existing `num_dynos_worker` which currently only works for Heroku.
